const GET_AUTH_START = 'GET_AUTH_START';
const GET_AUTH_SUCCESS = 'GET_AUTH_SUCCESS';
const GET_AUTH_FAILED = 'GET_AUTH_FAILED';

export {
    GET_AUTH_START,
    GET_AUTH_SUCCESS,
    GET_AUTH_FAILED,
};
